### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by windowz414** [windowz414/ce103-hw2-2022-2023-bedirhan-kurt#1]
- [x] Make initial README.
- [x] Develop required functions initially. Commit each implementation separately.
- [x] Run unit tests and ensure they pass. Remake/Edit function bodies if needed.
- [x] Generate Doxygen documentation.
- [x] Write report document.
- [x] Submit to Classroom.
